version: "3"

vars:
  RELEASE_DIR_WIN: "../releases/Kaimen"
  RELEASE_DIR_LINUX: "../dist/AppDir"
  CGO_WIN: '-IC:\PROGRA~2\WinFsp\inc\fuse'
  ONNX_LIB_WIN: "onnxruntime.dll"
  ONNX_LIB_LINUX: "libonnxruntime.so.1.26.0"
  ONNX_MODEL_URL: "https://huggingface.co/azuremountain/camie-tagger-v2_quantized/resolve/main/camie-tagger-v2_quantized.onnx"

tasks:
  _obtain-model:
    dir: backend
    status:
      - test -f camie-tagger-v2_quantized.onnx
    cmds:
      - echo "Downloading Onnx model..."
      - curl -L -o camie-tagger-v2_quantized.onnx "{{.ONNX_MODEL_URL}}"

  build-backend:
    dir: backend
    preconditions:
      - test -f go.mod
    env:
      CGO_CFLAGS: "{{.CGO_WIN}}"
    vars:
      LDFLAGS: '{{if .CLI_ARGS}}-s -w{{else}}-s -w -H=windowsgui{{end}}'
    cmds:
      - go build -ldflags="{{.LDFLAGS}}" -o kaimen.exe
      - task: _obtain-model
      - task: _copy-backend-assets
        vars:
          {
            TARGET: "{{.RELEASE_DIR_WIN}}",
            ONNX: "{{.ONNX_LIB_WIN}}",
            EXT: ".exe",
          }

  build-frontend:
    dir: frontend
    preconditions:
      - test -f pubspec.yaml
    cmds:
      - flutter build windows --release
      - cp -r build/windows/x64/runner/Release/. {{.RELEASE_DIR_WIN}}/

  build:
    desc: Build both backend and frontend
    cmds:
      - task: build-backend
      - task: build-frontend

  build-backend-linux:
    dir: backend
    preconditions:
      - test -f go.mod
    cmds:
      - go build -ldflags="-s -w" -o kaimen
      - task: _obtain-model
      - task: _copy-backend-assets
        vars:
          {
            TARGET: "{{.RELEASE_DIR_LINUX}}",
            ONNX: "{{.ONNX_LIB_LINUX}}",
            EXT: "",
          }

  build-frontend-linux:
    dir: frontend
    preconditions:
      - test -f pubspec.yaml
    cmds:
      - flutter build linux --release
      - mkdir -p {{.RELEASE_DIR_LINUX}}
      - rsync -a build/linux/x64/release/bundle/ {{.RELEASE_DIR_LINUX}}/

  appimage-cpy:
    dir: .
    cmds:
      - cp AppRun dist/AppDir
      - cp kaimen.desktop dist/AppDir
      - cp kaimen.png dist/AppDir
      - chmod +x dist/AppDir/AppRun

  build-linux:
    desc: Build both backend and frontend
    cmds:
      - task: build-backend-linux
      - task: build-frontend-linux
      - task: appimage-cpy

  # Internal helper task to remove copy-paste duplication
  _copy-backend-assets:
    internal: true
    dir: backend
    cmds:
      - mkdir -p {{.TARGET}}
      - cp kaimen{{.EXT}} {{.TARGET}}/kaimen{{.EXT}}
      - cp camie-tagger-v2_quantized.onnx {{.TARGET}}/camie-tagger-v2_quantized.onnx
      - cp camie-tagger-v2-metadata.json {{.TARGET}}/camie-tagger-v2-metadata.json
      - cp {{.ONNX}} {{.TARGET}}/{{.ONNX}}
