version: "3"

tasks:
  build-backend:
    dir: backend
    preconditions:
      - test -f go.mod
    env:
      CGO_CFLAGS: -IC:\PROGRA~2\WinFsp\inc\fuse
    cmds:
      - go build -ldflags="-s -w" -o kaimen.exe
      - cp kaimen.exe ../releases/Kaimen/kaimen.exe
      - cp camie-tagger-v2_quantized.onnx ../releases/Kaimen/camie-tagger-v2_quantized.onnx
      - cp camie-tagger-v2-metadata.json ../releases/Kaimen/camie-tagger-v2-metadata.json
      - cp onnxruntime.dll ../releases/Kaimen/onnxruntime.dll
  build-frontend:
    dir: frontend
    preconditions:
      - test -f pubspec.yaml
    cmds:
      - flutter build windows --release
      - cp -r build/windows/x64/runner/Release/. ../releases/Kaimen/
  build:
    desc: Build both backend and frontend
    cmds:
      - task: build-backend
      - task: build-frontend
